name: deploy-book

on:
  push:
    branches:
      - main
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: book
          environment-file: environment.yml
          python-version: 3.10
          auto-activate-base: false
      - name: Install dependencies
        run: |
          pip install -U jupyter-book ghp-import
      - name: Build the book
        run: |
          jupyter-book build .
      - name: Deploy to GitHub Pages
        run: |
          ghp-import -n -p -f _build/html